project:
  type: website
  output-dir: docs

website:
  title: "cheekypong"
  navbar:
    right:
      - about.qmd
      - icon: instagram
        text: Instagram
        href: https://www.instagram.com/cheekypong
      - icon: twitter
        text: Twitter
        href: https://twitter.com/cheepong89
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/leecheepong/
      - icon: github
        text: Github
        href: https://github.com/cheepong
format:
  html:
    theme: cosmo
    css: styles.css



